### ISSUE TITLE
加载图片资源时，如果输入的url是非法的会crash

### ISSUE THREAD

**Issue by yangdm0209** [vince-styling/Netroid#9]
ImageLoader.get传入非法url时会crash。查看代码发现

    public ImageContainer get(String requestUrl, ImageListener imageListener,
							  int maxWidth, int maxHeight) {
    .....
    ImageRequest newRequest = buildRequest(requestUrl, maxWidth, maxHeight);
    newRequest.setListener(new Listener<Bitmap>() {

如果url非法比如（23,12,32,12）会返回null，那么下面就的操作`newRequest.setListener`就会报异常

**Comment by vince-styling** [comment]
`ImageLoader.buildRequest()`是由开发者实现的，你可以在里面返回一个不做任何操作的Request对象作为默认结果，避免这个问题。
